### PR TITLE
Address review comments.

### PR DESCRIPTION
**Pull request by Argc0**
I addressed the problems mentioned in #255. 
The flag for converting to dnf has become `--convert-dnf`.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
The build has failed with a timeout.

**Comment by mbudiu-vmw** [comment]
I think we should merge this, even though the build timed-out.

**Comment by ryzhyk** [comment]
Yeah, Travis is not in good shape today.

**Comment by ryzhyk** [comment]
Thanks, @Argc0!

**Comment by Argc0** [comment]
I don't know why the build failed with time-out, everything was fine when I upload it.
You're welcome!!!

**Pull request merged**
