### PR TITLE
Java example with nested sets for redist.dl

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
You will probably need to update some dump outputs.

**Comment by mbudiu-vmw** [comment]
Yes, I was using the sorted map just for testing.
I will also convert the outer map to a fast map.
Are you getting the correct results?

**Comment by ryzhyk** [comment]
> Are you getting the correct results?

After 034fa980b8c3bae2ca442cabf78cc313074ed235 - yes (with TreeMap).

**Comment by mbudiu-vmw** [comment]
I have pushed a new change which has two implementations: one for testing with a RBTree and one for production with OpenHashMap. Unfortunately the code is a bit ugly now. In production you can delete much of the code. The OpenHashMap is about 2x faster than the RBTree.

**Pull request merged**
